# Generated by Django 5.1.2 on 2024-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, default='Visuel non disponible', upload_to='images/'),
        ),
    ]
