# Generated by Django 5.1.2 on 2024-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_alter_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, default='no-image', null=True, upload_to='images/'),
        ),
    ]
