# Generated by Django 5.1.2 on 2024-12-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_alter_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
