# Generated by Django 5.1.2 on 2024-12-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_title_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('title_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.title')),
            ],
        ),
    ]
