# Generated by Django 5.1.2 on 2024-12-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='title_id',
            new_name='title',
        ),
    ]
