# Generated by Django 5.1.2 on 2024-12-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_rename_title_id_reservation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='title',
            new_name='title_id',
        ),
    ]
