# Generated by Django 5.1.2 on 2024-12-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_rename_title_reservation_title_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='status',
            new_name='reserve',
        ),
    ]
