# Generated by Django 5.1.2 on 2024-12-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_rename_status_title_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='reserve',
            new_name='status',
        ),
    ]
