# Generated by Django 5.1.2 on 2024-12-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_alter_reservation_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='title_id',
            new_name='title',
        ),
    ]
